// <auto-generated />
using System;
using Lab2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121015106_addnewdatabas")]
    partial class addnewdatabas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4a465a8-0b83-4b69-8d9c-8c3aa6728121",
                            Email = "tdakhoa14012005@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Anh Khoa",
                            NormalizedEmail = "TDAKHOA14012005@GMAIL.COM",
                            NormalizedUserName = "TDAKHOA14012005@GMAIL.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAENJ+6nmE7d0UFC3Wo0Y0A7XpXMVviVOdp7J0/K2Q5MIY5S2WhlMv06J2UNMowxMMtQ==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            SecurityStamp = "f0493b6e-8b01-461d-8044-0decfa7c25cc",
                            TwoFactorEnabled = false,
                            UserName = "tdakhoa14012005@gmail.com"
                        },
                        new
                        {
                            Id = "002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be27cb12-11ac-4974-b533-b5c424d36ccf",
                            Email = "hatakeiku450@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Anh Khoa 2",
                            NormalizedEmail = "HATAKEIKU450@GMAIL.COM",
                            NormalizedUserName = "HATAKEIKU450@GMAIL.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEKMInokm1jb5zv1KzjaGb5YpUl24dBTQf/m2uJtTdWkRu9ovIxW9ekwlaju7HFbPOw==",
                            PhoneNumberConfirmed = false,
                            RegionId = 2,
                            SecurityStamp = "7f86170e-597a-4e81-a72f-1957ee47f3af",
                            TwoFactorEnabled = false,
                            UserName = "hatakeiku450@gmail.com"
                        },
                        new
                        {
                            Id = "003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d81c56ab-c680-475f-84c8-59eb95030951",
                            Email = "anhkhoa123@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Anh Khoa 3",
                            NormalizedEmail = "ANHKHOA123@GMAIL.COM",
                            NormalizedUserName = "ANHKHOA123@GMAIL.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEKMInokm1jb5zv1KzjaGb5YpUl24dBTQf/m2uJtTdWkRu9ovIxW9ekwlaju7HFbPOw==",
                            PhoneNumberConfirmed = false,
                            RegionId = 3,
                            SecurityStamp = "f9f48ec6-83c9-4143-9bfb-cc6a2f916937",
                            TwoFactorEnabled = false,
                            UserName = "anhkhoa123@gmail.com"
                        },
                        new
                        {
                            Id = "004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acb0511e-0b02-4ff8-bb16-a2d0d055d7ec",
                            Email = "user4@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 4",
                            NormalizedEmail = "USER4@EXAMPLE.COM",
                            NormalizedUserName = "USER4@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            SecurityStamp = "3f6ce5f6-57e9-4cec-9117-b8817dd1a548",
                            TwoFactorEnabled = false,
                            UserName = "user4@example.com"
                        },
                        new
                        {
                            Id = "005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "576e22cc-609f-49c7-b61d-4e3b223f8f5e",
                            Email = "user5@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 5",
                            NormalizedEmail = "USER5@EXAMPLE.COM",
                            NormalizedUserName = "USER5@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 2,
                            SecurityStamp = "72bc2ea9-da8c-48b4-804e-3cc4b93f0846",
                            TwoFactorEnabled = false,
                            UserName = "user5@example.com"
                        },
                        new
                        {
                            Id = "006",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f9cfe1d-c949-452e-9722-b3168417869c",
                            Email = "user6@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 6",
                            NormalizedEmail = "USER6@EXAMPLE.COM",
                            NormalizedUserName = "USER6@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 3,
                            SecurityStamp = "06f90de8-ebd6-418c-85e9-2ed2db12ad84",
                            TwoFactorEnabled = false,
                            UserName = "user6@example.com"
                        },
                        new
                        {
                            Id = "007",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "339f4939-415f-4107-9b4b-b8bc7d432333",
                            Email = "user7@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 7",
                            NormalizedEmail = "USER7@EXAMPLE.COM",
                            NormalizedUserName = "USER7@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            SecurityStamp = "38682f07-fd73-4e02-8625-6975489aefb0",
                            TwoFactorEnabled = false,
                            UserName = "user7@example.com"
                        },
                        new
                        {
                            Id = "008",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "159da5f6-d3b1-4704-ab73-deebb13fc651",
                            Email = "user8@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 8",
                            NormalizedEmail = "USER8@EXAMPLE.COM",
                            NormalizedUserName = "USER8@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 2,
                            SecurityStamp = "74a80770-8083-4540-a341-35e5316c9910",
                            TwoFactorEnabled = false,
                            UserName = "user8@example.com"
                        },
                        new
                        {
                            Id = "009",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7dd063f-6c9d-48fc-814b-e89897472ec4",
                            Email = "user9@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 9",
                            NormalizedEmail = "USER9@EXAMPLE.COM",
                            NormalizedUserName = "USER9@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 3,
                            SecurityStamp = "25bffdcb-17ff-4f3a-bcd5-5065316772bd",
                            TwoFactorEnabled = false,
                            UserName = "user9@example.com"
                        },
                        new
                        {
                            Id = "010",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cfcd55d3-a2ec-4e33-bada-0c682da1015c",
                            Email = "user10@example.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Người dùng 10",
                            NormalizedEmail = "USER10@EXAMPLE.COM",
                            NormalizedUserName = "USER10@EXAMPLE.COM",
                            OTP = "initial",
                            PasswordHash = "AQAAAAIAAYagAAAAEB1rFDMkr/6RaTLgs4Rc+a7OaKu1oPODEoVRlLg18YelqvBeXo7z3/5GJQCCdtl5Xg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            SecurityStamp = "5e3fcd4e-4588-46a9-b0e4-2a9e3c06f115",
                            TwoFactorEnabled = false,
                            UserName = "user10@example.com"
                        });
                });

            modelBuilder.Entity("Lab2.Models.GameLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LevelId");

                    b.ToTable("GameLevels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Title = "Cấp độ 1"
                        },
                        new
                        {
                            LevelId = 2,
                            Title = "Cấp độ 2"
                        },
                        new
                        {
                            LevelId = 3,
                            Title = "Cấp độ 3"
                        });
                });

            modelBuilder.Entity("Lab2.Models.LevelResult", b =>
                {
                    b.Property<int>("QuizResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizResultId"));

                    b.Property<DateOnly>("CompletionDate")
                        .HasColumnType("date");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuizResultId");

                    b.ToTable("LevelResults");
                });

            modelBuilder.Entity("Lab2.Models.Quession", b =>
                {
                    b.Property<int>("QuessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuessionId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentQuession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("levelId")
                        .HasColumnType("integer");

                    b.HasKey("QuessionId");

                    b.ToTable("Quessions");

                    b.HasData(
                        new
                        {
                            QuessionId = 1,
                            Answer = "Đáp án 1",
                            ContentQuession = "Câu hỏi 1",
                            Option1 = "Đáp án 1",
                            Option2 = "Đáp án 2",
                            Option3 = "Đáp án 3",
                            Option4 = "Đáp án 4",
                            levelId = 1
                        },
                        new
                        {
                            QuessionId = 2,
                            Answer = "Đáp án 2",
                            ContentQuession = "Câu hỏi 2",
                            Option1 = "Đáp án 1",
                            Option2 = "Đáp án 2",
                            Option3 = "Đáp án 3",
                            Option4 = "Đáp án 4",
                            levelId = 2
                        });
                });

            modelBuilder.Entity("Lab2.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Đồng bằng sông hồng"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Đồng bằng sông cửu long"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Lab2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Lab2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Lab2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
